
vocabulary = {
    1: {
        "block": {"name":["block"]},
        "blocks": {"name":["blocks"]},
        "object_general_name": {"name":["shape", "thing", "object"]},
        "objects_general_name": {"name":["shapes", "things", "objects"]},
        "block_name": {"0": "AAA", "1": "BBB", "2": "CCC"},
        "color": {"yellow": "yellow", "black": "black", "#0099ff": "blue"},
        "size": {10: "small", 20: "medium", 30: "big"},
        "type": {"circle": "circle", "square": "square", "triangle": "triangle"},
        "types": {"circle": "circles", "square": "squares", "triangle": "triangles"},
    },
    2: {
        "block": {"name":["box"]},
        "blocks": {"name":["boxes"]},
        "object_general_name": {"name":["shape", "thing", "object"]},
        "objects_general_name": {"name":["shapes", "things", "objects"]},
        "block_name": {"0": "DDD", "1": "EEE", "2": "JJJ"},
        "color": {"yellow": "orange", "black": "white", "#0099ff": "green"},
        "size": {10: "tiny", 20: "midsize", 30: "large"},
        "type": {"circle": "oval", "square": "rectangle", "triangle": "dimond"},
        "types": {"circle": "ovals", "square": "rectangles", "triangle": "dimonds"},
    },
    3: {
        "block": {"name":["block"]},
        "blocks": {"name":["blocks"]},
        "object_general_name": {"name":["shape", "thing", "object"]},
        "objects_general_name": {"name":["shapes", "things", "objects"]},
        "block_name": {"0": "HHH", "1": "LLL", "2": "KKK"},
        "color": {"yellow": "red", "black": "grey", "#0099ff": "purple"},
        "size": {10: "little", 20: "medium", 30: "large"},
        "type": {"circle": "pentagon", "square": "hexagon", "triangle": "star"},
        "types": {"circle": "pentagons", "square": "hexagons", "triangle": "stars"},
    }, 
    4: {
        "block": {"name":["box"]},
        "blocks": {"name":["boxes"]},
        "object_general_name": {"name":["thing", "fruit"]},
        "objects_general_name": {"name":["things", "fruits"]},
        "block_name": {"0": "one", "1": "two", "2": "three"},
        "color": {"yellow": "yellow", "black": "green", "#0099ff": "orange"},
        "size": {10: "small", 20: "medium", 30: "big"},
        "type": {"circle": "watermelon", "square": "apple", "triangle": "melon"},
        "types": {"circle": "watermelons", "square": "apples", "triangle": "melons"},
    },
    # {
    #     "block": {"name":["house"]},
    #     "object_general_name": {"name":["building"]},
    #     "block_name": {"0": "one", "1": "two", "2": "three"},
    #     "color": {"yellow": "yellow", "black": "green", "#0099ff": "red"},
    #     "size": {10: "small", 20: "midsize", 30: "large"},
    #     "shape": {"circle": "bedroom", "square": "livingroom", "triangle": "basement"},
        
    # }
}

relation_vocabulary = {
    1: {
        "relation": {
            "LEFT": "left",
            "RIGHT": "right",
            "ABOVE": "above",
            "BELOW": "below",
            "BEHIND": "behind",
            "FRONT": "front",
            "NEAR": "near",
            "FAR": "far",
            "DC": "disconnected",
            "EC": "touch",
            "PO": "overlap",
            "TPP": "covered by",
            "NTPP": "in",
            "TPPI": "cover",
            "NTPPI": "has",
        },
        "relation_in_text": {
            "LEFT": ["to the left of", "on the left side of", "to the left-hand side of"],
            "RIGHT": ["to the right of", "on the right side of", "to the right-hand side of"],
            "ABOVE": ["above", "over"],
            "BELOW": ["below", "under"],
            "BEHIND": ["behind", "on the back of"],
            "FRONT": ["in front of"],
            "NEAR": ["near to", "close to"],
            "FAR": ["far from", "farther from", "away from"],
            "DC": "disconnected from",
            "EC": "touch[es]",
            # "EC": "touch[es] the [rel] of",
            "PO": "overlap[s]",
#             "TPP": "touch[es] the inner [rel] edge of",
            "TPP": ["covered by", "inside and touching"],
            # "TPP": ["the [rel] edge of [obj] [is/are] covered by", "[is/are] inside and touch[es] the [rel] edge of"],
            # "TPP": "inside and touch[es] the [rel] edge of",
            "NTPP": ["in", "inside", "within"],
            # "TPPI": "from the [rel] edge cover[s]",
            "TPPI": ["cover[s]"],
            # "TPPI": "cover[s] the [rel] edge of",
#             "TPPI": ["ha[s/ve] and touch[es] the [rel] edge of", "contain[s] and touch[es] the [rel] edge of"],
            "NTPPI": ["ha[s/ve]","contain[s]"],
        },
        "relation_in_question": {
            "LEFT": ["to the left of", "on the left side of", "to the left-hand side of"],
            "RIGHT": ["to the right of", "on the right side of", "to the right-hand side of"],
            "ABOVE": ["above", "over"],
            "BELOW": ["below", "under"],
            "NEAR": ["near to", "close to"],
            "FAR": ["far from", "farther from", "away from"],
            "DC": "disconnected from",
            "EC": "touching",
            "PO": "overlapping",
#             "TPP": "touch[es] the inner [rel] edge of",
            "TPP": ["covered by", "touching", "in", "inside", "within"],
            # "TPP": "inside and touch[es] the [rel] edge of",
            "NTPP": ["in", "inside", "within"],
            # "TPPI": "from the [rel] edge cover[s]",
            "TPPI": ["covering", "touching", "having","containing"],
#             "TPPI": ["ha[s/ve] and touch[es] the [rel] edge of", "contain[s] and touch[es] the [rel] edge of"],
            "NTPPI": ["having","containing"],
        },
    },
    2: { # use cardinal relations
        "relation": {
            "LEFT": "west",
            "RIGHT": "east",
            "ABOVE": "north",
            "BELOW": "south",
            "BEHIND": "behind",
            "FRONT": "front",
            "NEAR": "near",
            "FAR": "far",
            "DC": "disconnected",
            "EC": "touch",
            "PO": "overlap",
            "TPP": "covered by",
            "NTPP": "in",
            "TPPI": "cover",
            "NTPPI": "has",
        },
        "relation_in_text": {
            "LEFT": ["west of", "to the west of"],
            "RIGHT": ["east of", "to the east of"],
            "ABOVE": ["north of", "to the north of"],
            "BELOW": ["south of", "to the south of"],
            "BEHIND": ["behind", "on the back of"],
            "FRONT": ["in front of"],
            "NEAR": ["near to", "close to"],
            "FAR": ["far from", "farther from", "away from"],
            "DC": "disconnected from",
            "EC": "touch[es]",
            # "EC": "touch[es] the [rel] of",
            "PO": "overlap[s]",
#             "TPP": "touch[es] the inner [rel] edge of",
            "TPP": ["covered by", "inside and touching"],
            # "TPP": ["the [rel] edge of [obj] [is/are] covered by", "[is/are] inside and touch[es] the [rel] edge of"],
            # "TPP": "inside and touch[es] the [rel] edge of",
            "NTPP": ["in", "inside", "within"],
            # "TPPI": "from the [rel] edge cover[s]",
            "TPPI": ["cover[s]"],
            # "TPPI": "cover[s] the [rel] edge of",
#             "TPPI": ["ha[s/ve] and touch[es] the [rel] edge of", "contain[s] and touch[es] the [rel] edge of"],
            "NTPPI": ["ha[s/ve]","contain[s]"],
        },
        "relation_in_question": {
            "LEFT": ["west of", "to the west of"],
            "RIGHT": ["east of", "to the east of"],
            "ABOVE": ["north of", "to the north of"],
            "BELOW": ["south of", "to the south of"],
            "NEAR": ["near to", "close to"],
            "FAR": ["far from", "farther from", "away from"],
            "DC": "disconnected from",
            "EC": "touching",
            "PO": "overlapping",
#             "TPP": "touch[es] the inner [rel] edge of",
            "TPP": ["covered by", "touching", "in", "inside", "within"],
            # "TPP": "inside and touch[es] the [rel] edge of",
            "NTPP": ["in", "inside", "within"],
            # "TPPI": "from the [rel] edge cover[s]",
            "TPPI": ["covering", "touching", "having","containing"],
#             "TPPI": ["ha[s/ve] and touch[es] the [rel] edge of", "contain[s] and touch[es] the [rel] edge of"],
            "NTPPI": ["having","containing"],
        },
    },
    3: { #use oclock positions
        "relation": {
            "LEFT": "9",
            "RIGHT": "3",
            "ABOVE": "12",
            "BELOW": "6",
            "BEHIND": "behind",
            "FRONT": "front",
            "NEAR": "near",
            "FAR": "far",
            "DC": "disconnected",
            "EC": "touch",
            "PO": "overlap",
            "TPP": "covered by",
            "NTPP": "in",
            "TPPI": "cover",
            "NTPPI": "has",
        },
        "relation_in_text": {
            "LEFT": ["at 9:00 position relative to", "at 9:00 position regarding to", "at 9 o'clock position regarding to"],
            "RIGHT": ["at 3:00 position relative to", "at 3:00 position regarding to", "at 3 o'clock position regarding to"],
            "ABOVE": ["at 12:00 position relative to", "at 12:00 position regarding to", "at 12 o'clock position regarding to"],
            "BELOW": ["at 6:00 position relative to", "at 6:00 position regarding to", "at 6 o'clock position regarding to"],
            "BEHIND": ["behind", "on the back of"],
            "FRONT": ["in front of"],
            "NEAR": ["near to", "close to"],
            "FAR": ["far from", "farther from", "away from"],
            "DC": "disconnected from",
            "EC": "touch[es]",
            # "EC": "touch[es] the [rel] of",
            "PO": "overlap[s]",
#             "TPP": "touch[es] the inner [rel] edge of",
            "TPP": ["covered by", "inside and touching"],
            # "TPP": ["the [rel] edge of [obj] [is/are] covered by", "[is/are] inside and touch[es] the [rel] edge of"],
            # "TPP": "inside and touch[es] the [rel] edge of",
            "NTPP": ["in", "inside", "within"],
            # "TPPI": "from the [rel] edge cover[s]",
            "TPPI": ["cover[s]"],
            # "TPPI": "cover[s] the [rel] edge of",
#             "TPPI": ["ha[s/ve] and touch[es] the [rel] edge of", "contain[s] and touch[es] the [rel] edge of"],
            "NTPPI": ["ha[s/ve]","contain[s]"],
        },
        "relation_in_question": {
            "LEFT": ["at 9:00 position relative to", "at 9:00 position regarding to", "at 9 o'clock position regarding to"],
            "RIGHT": ["at 3:00 position relative to", "at 3:00 position regarding to", "at 3 o'clock position regarding to"],
            "ABOVE": ["at 12:00 position relative to", "at 12:00 position regarding to", "at 12 o'clock position regarding to"],
            "BELOW": ["at 6:00 position relative to", "at 6:00 position regarding to", "at 6 o'clock position regarding to"],
            "NEAR": ["near to", "close to"],
            "FAR": ["far from", "farther from", "away from"],
            "DC": "disconnected from",
            "EC": "touching",
            "PO": "overlapping",
#             "TPP": "touch[es] the inner [rel] edge of",
            "TPP": ["covered by", "touching", "in", "inside", "within"],
            # "TPP": "inside and touch[es] the [rel] edge of",
            "NTPP": ["in", "inside", "within"],
            # "TPPI": "from the [rel] edge cover[s]",
            "TPPI": ["covering", "touching", "having","containing"],
#             "TPPI": ["ha[s/ve] and touch[es] the [rel] edge of", "contain[s] and touch[es] the [rel] edge of"],
            "NTPPI": ["having","containing"],
        },
    },
    4: {
        "relation": {
            "LEFT": "left",
            "RIGHT": "right",
            "ABOVE": "above",
            "BELOW": "below",
            "BEHIND": "behind",
            "FRONT": "front",
            "NEAR": "near",
            "FAR": "far",
            "DC": "disconnected",
            "EC": "touch",
            "PO": "overlap",
            "TPP": "covered by",
            "NTPP": "in",
            "TPPI": "cover",
            "NTPPI": "has",
        },
        "relation_in_text": {
            "LEFT": ["to the left of"],
            "RIGHT": ["to the right of"],
            "ABOVE": ["above"],
            "BELOW": ["below"],
            "BEHIND": ["behind"],
            "FRONT": ["in front of"],
            "NEAR": ["near to"],
            "FAR": ["far from"],
            "DC": "disconnected from",
            "EC": "touch[es]",
            # "EC": "touch[es] the [rel] of",
            "PO": "overlap[s]",
#             "TPP": "touch[es] the inner [rel] edge of",
            "TPP": ["covered by"],
            # "TPP": ["the [rel] edge of [obj] [is/are] covered by", "[is/are] inside and touch[es] the [rel] edge of"],
            # "TPP": "inside and touch[es] the [rel] edge of",
            "NTPP": ["in"],
            # "TPPI": "from the [rel] edge cover[s]",
            "TPPI": ["cover[s]"],
            # "TPPI": "cover[s] the [rel] edge of",
#             "TPPI": ["ha[s/ve] and touch[es] the [rel] edge of", "contain[s] and touch[es] the [rel] edge of"],
            "NTPPI": ["contain[s]"],
        },
        "relation_in_question": {
            "LEFT": ["to the left of"],
            "RIGHT": ["to the right of"],
            "ABOVE": ["above"],
            "BELOW": ["below"],
            "NEAR": ["near to"],
            "FAR": ["far from"],
            "DC": "disconnected from",
            "EC": "touching",
            "PO": "overlapping",
#             "TPP": "touch[es] the inner [rel] edge of",
            "TPP": ["covered by"],
            # "TPP": "inside and touch[es] the [rel] edge of",
            "NTPP": ["in"],
            # "TPPI": "from the [rel] edge cover[s]",
            "TPPI": ["covering"],
#             "TPPI": ["ha[s/ve] and touch[es] the [rel] edge of", "contain[s] and touch[es] the [rel] edge of"],
            "NTPPI": ["containing"],
        },
    },
}




# Paris is in the north of France.
# Sweden is north of France.
# Belgium is to the north of France.
# Canada is north of the USA.
# The USA is north of Mexico
# Mexico is south of the USA.
# Moscow is in the west of Russia.
# Europe is west of Russia.
# Europe is to the west of Russia.
# Shanghai is in the east of China.
# Japan is east of China.
# Japan is to the east of China.